export const SELECT_MONTH = 'SELECT_MONTH';
export const SELECT_YEAR = 'SELECT_YEAR';

export const TOGGLE_MONTH_SELECTOR = 'TOGGLE_MONTH_SELECTOR';
export const TOGGLE_YEAR_SELECTOR = 'TOGGLE_YEAR_SELECTOR';

export const ON_PREV_CALENDAR_CLICK = 'ON_PREV_CALENDAR_CLICK';
export const ON_NEXT_CALENDAR_CLICK = 'ON_NEXT_CALENDAR_CLICK';

export const FETCH_EVENT_LIST_START = 'FETCH_EVENT_LIST_START';
export const FETCH_EVENT_LIST_SUCCESS = 'FETCH_EVENT_LIST_SUCCESS';
export const FETCH_EVENT_LIST_FAILED = 'FETCH_EVENT_LIST_FAILED';

export const FETCH_GUEST_EVENT_LIST_START = 'FETCH_GUEST_EVENT_LIST_START';
export const FETCH_GUEST_EVENT_LIST_SUCCESS = 'FETCH_GUEST_EVENT_LIST_SUCCESS';
export const FETCH_GUEST_EVENT_LIST_FAILED = 'FETCH_GUEST_EVENT_LIST_FAILED';

export const CREATE_EVENT_INIT = 'CREATE_EVENT_INIT';
export const CREATE_EVENT_START = 'CREATE_EVENT_START';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILED = 'CREATE_EVENT_FAILED';

export const DELETE_EVENT_START = 'DELETE_EVENT_START';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const CHAT_INPUT_CHANGED = 'CHAT_INPUT_CHANGED';
export const SEND_MSG_START = 'SEND_MSG_START';
export const SEND_MSG_SUCCESS = 'SEND_MSG_SUCCESS';
export const SEND_MSG_FAILED = 'SEND_MSG_FAILED';

export const SET_CHAT_EVENT_ID = 'SET_CHAT_EVENT_ID';
export const FETCH_CHATS_START = 'FETCH_CHATS_START';
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_FAILED = 'FETCH_CHATS_FAILED';

export const SEND_GUEST_INVITE_START = 'SEND_GUEST_INVITE_START';
export const SEND_GUEST_INVITE_SUCCESS = 'SEND_GUEST_INVITE_SUCCESS';
export const SEND_GUEST_INVITE_EXISTS = 'SEND_GUEST_INVITE_EXISTS';
export const SEND_GUEST_INVITE_NOT_EXISTS = 'SEND_GUEST_INVITE_NOT_EXISTS';
export const SEND_GUEST_INVITE_FAILED = 'SEND_GUEST_INVITE_FAILED';

export const FETCH_CHAT_MEMBERS_START = 'FETCH_CHAT_MEMBERS_START';
export const FETCH_CHAT_MEMBERS_SUCCESS = 'FETCH_CHAT_MEMBERS_SUCCESS';
export const FETCH_CHAT_MEMBERS_FAILED = 'FETCH_CHAT_MEMBERS_FAILED';