export const SELECT_MONTH = 'SELECT_MONTH';
export const SELECT_YEAR = 'SELECT_YEAR';

export const TOGGLE_MONTH_SELECTOR = 'TOGGLE_MONTH_SELECTOR';
export const TOGGLE_YEAR_SELECTOR = 'TOGGLE_YEAR_SELECTOR';

export const ON_PREV_CALENDAR_CLICK = 'ON_PREV_CALENDAR_CLICK';
export const ON_NEXT_CALENDAR_CLICK = 'ON_NEXT_CALENDAR_CLICK';

export const FETCH_EVENTS_FROM_BACKEND = 'FETCH_EVENTS_FROM_BACKEND';
export const SET_EVENT_LIST = 'SET_EVENT_LIST';
export const FETCH_EVENT_LIST_FAILED = 'FETCH_EVENT_LIST_FAILED';

// export const ON_DAY_CLICK = 'ON_DAY_CLICK';
// export const ON_CREATE_EVENT_CANCEL = 'ON_CREATE_EVENT_CANCEL';
// export const ON_DELETE_EVENT_CLICK = 'ON_DELETE_EVENT_CLICK';
// export const ON_DELETE_EVENT_CONFIRM = 'ON_DELETE_EVENT_CONFIRM';